# Makefile.deps created Tue May  5 08:44:31 PDT 2015 by make
astree.o: astree.cc astree.h auxlib.h stringset.h lyutils.h yyparse.h
lyutils.o: lyutils.cc lyutils.h astree.h auxlib.h yyparse.h
auxlib.o: auxlib.cc auxlib.h
stringset.o: stringset.cc stringset.h auxlib.h
main.o: main.cc astree.h auxlib.h lyutils.h yyparse.h stringset.h
yylex.o: yylex.cc auxlib.h lyutils.h astree.h yyparse.h
yyparse.o: yyparse.cc lyutils.h astree.h auxlib.h yyparse.h
