source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target 'Nibble' do
pod 'Parse'
pod 'AHKNavigationController'
pod 'SDWebImage', '~>3.7'
pod 'FBSDKCoreKit'
pod 'ParseFacebookUtilsV4'
end

target 'Watch Extension' do
pod 'Parse'
end